{%- if cookiecutter.documentation_tool == "mkdocs-material" -%}
site_name: {{ cookiecutter.project_name }}
site_description: {{ cookiecutter.project_description }}
site_author: {{ cookiecutter.author_name }}
site_url: https://{{ cookiecutter.github_username }}.github.io/{{ cookiecutter.project_slug }}

repo_name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}

docs_dir: content

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [".."]  # Add parent directory to Python path
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            separate_signature: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Quick Start: quickstart.md
    - Examples: examples.md
  - User Guide:
    - Core Concepts: concepts.md
{%- if cookiecutter.use_async == "yes" %}
    - Synchronous API: sync-api.md
    - Asynchronous API: async-api.md
{%- else %}
    - API Guide: api-guide.md
{%- endif %}
{%- if cookiecutter.database_backend != "none" %}
    - Database Integration: database.md
{%- endif %}
  - API Reference:
    - Overview: api/index.md
    - Core Module: api/core.md
{%- if cookiecutter.use_async == "yes" %}
    - Async Module: api/async.md
{%- endif %}
{%- if cookiecutter.database_backend != "none" %}
    - Database Module: api/database.md
{%- endif %}
  - Developer Documentation:
    - Contributing: developer/contributing.md
    - Testing: developer/testing.md
    - Development Setup: developer/setup.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{ cookiecutter.package_name }}

watch:
  - ../{{ cookiecutter.package_name }}/
{%- endif -%}