[project]
name = "vibe-py-cookiecutter"
version = "0.1.0"
description = "Modern Python project cookiecutter template with comprehensive tooling"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[dependencies]
python = ">=3.12,<3.13"
# Core dependencies
tenacity = ">=9.1.2,<10"

[feature.dev.dependencies]
# Testing
pytest = "*"
pytest-cookies = ">=0.7.0"
pytest-cov = ">=4.0.0"
cookiecutter = ">=2.1.0"
coverage = ">=7.0.0,<8"
# Code quality
mypy = "*"
ruff = "*"
pre-commit = ">=4.2.0,<5"
# CLI tools
typer = ">=0.9.0,<1"
rich = ">=13.0.0,<14"

[pypi-dependencies]
sh = ">=2.0.0,<3"

[environments]
default = ["dev"]
dev = ["dev"]

[tasks]
# Unified task scripts (following cookiecutter pattern)
quality = { cmd = "python scripts/quality.py", description = "Code quality management (linting, formatting, type checking)" }
dev = { cmd = "python scripts/dev.py", description = "Development environment management (setup, status, clean)" }
test = { cmd = "python scripts/test.py", description = "Testing management (unit, integration, cookiecutter generation)" }

# Unified operations
clean = { cmd = "python scripts/test.py clean && python scripts/dev.py clean", description = "Clean all project artifacts" }
check-all = { cmd = "python scripts/test.py all && python scripts/quality.py check", description = "Run comprehensive checks (all tests + quality)" }