name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_only:
        description: 'Test build only (do not publish)'
        required: false
        default: 'false'
        type: boolean

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.34.0
        cache: true

    - name: Install dependencies
      run: pixi install

    - name: Run quality checks
      run: pixi run quality check

    - name: Run tests
      run: pixi run test all

    - name: Build package
      run: pixi run build package

    - name: Check package
      run: pixi run build check

    - name: Test upload to TestPyPI
      if: github.event_name == 'workflow_dispatch' && inputs.test_only == 'true'
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ "{{" }} secrets.TEST_PYPI_API_TOKEN {{ "}}" }}
      run: pixi run build upload --repository testpypi

    - name: Publish to PyPI
      if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.test_only == 'false')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ "{{" }} secrets.PYPI_API_TOKEN {{ "}}" }}
      run: pixi run build upload --repository pypi

{%- if cookiecutter.documentation_tool == 'mkdocs-material' %}
    - name: Deploy documentation
      if: github.event_name == 'release'
      run: pixi run docs deploy --message "📚 Update docs for release ${{ "{{" }} github.event.release.tag_name {{ "}}" }}"
{%- endif %}