name: Security

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '{{ cookiecutter.python_version }}'

    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml] safety

    - name: Run Bandit security scanner
      run: |
        bandit -r {{ cookiecutter.package_name }}/ -f json -o bandit-report.json || true
        bandit -r {{ cookiecutter.package_name }}/ -f txt

    - name: Upload Bandit scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: bandit-report.json

    - name: Run Safety to check dependencies
      run: |
        # Create requirements file from current environment
        pip freeze > requirements-temp.txt
        safety check -r requirements-temp.txt --json --output safety-report.json || true
        safety check -r requirements-temp.txt
        rm requirements-temp.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json